forge "https://forgeapi.puppetlabs.com"
mod 'puppetlabs-stdlib'
mod 'puppetlabs-apt'
mod 'puppetlabs-vcsrepo'
mod 'darin-zypprepo'

mod 'jenkins',
  :git => 'https://github.com/jenkinsci/puppet-jenkins.git'

mod 'sudoers',
  :git => 'https://github.com/pcfens/puppet-sudoers.git'

mod 'guest_additions',
  :git => 'git://github.com/pcfens/puppet-guest_additions'

mod 'tomcat7',
  :git => 'git://github.com/crpeck/tomcat7.git'
